### ISSUE TITLE
Timer has 3 timestamps

### ISSUE THREAD

**Issue by poy** [cloudfoundry/loggregator-api#3]
It has the envelope time, start and stop. It seems the stop timestamp would be redundant to the envelope time.

I believe the fix is to have the timer have a start time and a duration. This way the result of the timer is first class and we have less redundant data.

**Comment by jasonkeene** [comment]
@apoydence I'm not sure envelope timestamp is necessarily the same as timer's stop time. This might be something you guys should discuss with @ahevenor.

Changing to a duration might save some bytes when encoding the duration using [varint](https://developers.google.com/protocol-buffers/docs/encoding#varints). varints use less bytes for smaller values.

Considering this issue was open since Jan it should probably be closed or IPMed.

**Comment by poy** [comment]
I don't think we really have many timers flowing through our system yet. It might be best to wait and see how it all pans out when systems start emitting them.
